name: Build

on:
    workflow_dispatch:
        inputs:
            boost_version:
                description: "Boost verion in format 1_74_0"
                default: "1_74_0"

jobs:
    Linux_build:
        strategy:
            matrix:
                pic: [ "PIC", "noPIC" ]
                os: [ "debian-buster", "ubuntu-2004", "ubuntu-1804" ]
        runs-on: ubuntu-latest
        container:
            image: koudis/boost-build:${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: 'Build'
              run: ./unix.sh ${{ matrix.os }} ${{ github.event.inputs.boost_version }} ${{ matrix.pic }}
            - name: 'Upload Artifacts'
              uses: actions/upload-artifact@v2
              with:
                  name: "boost"
                  path: "boost_archive/"

    Macos_build:
        strategy:
            matrix:
                pic: [ "PIC", "noPIC" ]
                os: [ "macos-11.0", "macos-10.15" ]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: 'Build'
              run: ./unix.sh ${{ matrix.os }} ${{ github.event.inputs.boost_version }} ${{ matrix.pic }}
            - name: 'Upload Artifacts'
              uses: actions/upload-artifact@v2
              with:
                  name: "boost"
                  path: "boost_archive/"

    Release:
        name: Create Release
        needs: [ Linux_build, Macos_build ]
        runs-on: ubuntu-latest
        outputs:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
        steps:
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.event.inputs.boost_version }}
                  release_name: Release ${{ github.event.inputs.boost_version }}
                  body: Boost ${{ github.event.inputs.boost_version }} release 
                  draft: true
                  prerelease: false

    Upload_release_asset:
        name: Upload release assets
        strategy:
            matrix:
                pic: [ "PIC", "noPIC" ]
                os: [ "debian_buster", "ubuntu_2004", "ubuntu_1804", "macos_10_15", "macos_11_0"  ]
        needs: [ Release ]
        runs-on: ubuntu-latest
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v2
            - name: Upload Release Asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ needs.Release.outputs.upload_url }}
                  asset_path: ./boost/boost-${{ github.event.inputs.boost_version }}-${{ matrix.os }}-${{ matrix.pic }}.tar.bz2
                  asset_name: boost-${{ github.event.inputs.boost_version }}-${{ matrix.os }}-${{ matrix.pic }}.tar.bz2
                  asset_content_type: application/gzip
