name: Build

on:
    workflow_dispatch:
        inputs:
            boost_version:
                description: "Boost verion in format 1_74_0"
                default: "1_74_0"

jobs:
    Linux_build:
        strategy:
            matrix:
                pic: [ "PIC", "" ]
                os: [ "debian-buster", "ubuntu-1804", "ubuntu-2004" ]
        runs-on: ubuntu-latest
        container:
            image: koudis/boost-build:${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: 'Build'
              run: ./unix.sh ${{ matrix.os }} ${{ github.event.inputs.boost_version }} ${{ matrix.pic }}
            - name: 'Upload Artifacts'
              uses: actions/upload-artifact@v2
              with:
                  name: "boost"
                  path: "boost_archive/"

    Macos_build:
        strategy:
            matrix:
                pic: [ "PIC", "" ]
                os: [ "macos-11.0", "macos-10.15" ]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: 'Build'
              run: ./unix.sh ${{ matrix.os }} ${{ github.event.inputs.boost_version }} ${{ matrix.pic }}
            - name: 'Upload Artifacts'
              uses: actions/upload-artifact@v2
              with:
                  name: "boost"
                  path: "boost_archive/"
